"""Tests for pineapple_upgrade.py -- template version comparison and upgrade detection.

All tests use tmp_path fixtures and have no real filesystem dependencies.
"""

from pineapple_upgrade import (
    TemplateStatus,
    UpgradeReport,
    _extract_version,
    check_templates,
    show_diff,
    TEMPLATE_DESTINATIONS,
)


# ---------------------------------------------------------------------------
# _extract_version
# ---------------------------------------------------------------------------


class TestExtractVersion:
    def test_extract_standard_header(self):
        text = "# Pineapple Pipeline v1.2.3\nsome content"
        assert _extract_version(text) == "1.2.3"

    def test_extract_from_comment(self):
        text = "# Generated by Pineapple Pipeline v2.0.0\n"
        assert _extract_version(text) == "2.0.0"

    def test_extract_no_version(self):
        text = "just some file content without version"
        assert _extract_version(text) == ""

    def test_extract_multidigit(self):
        text = "Pineapple Pipeline v10.20.300"
        assert _extract_version(text) == "10.20.300"

    def test_extract_embedded_in_text(self):
        text = "This file was created by Pineapple Pipeline v1.0.0 on 2025-01-01"
        assert _extract_version(text) == "1.0.0"


# ---------------------------------------------------------------------------
# UpgradeReport
# ---------------------------------------------------------------------------


class TestUpgradeReport:
    def test_outdated_count_zero(self):
        report = UpgradeReport(
            templates=[
                TemplateStatus("t1", "f1", "current"),
                TemplateStatus("t2", "f2", "missing"),
            ]
        )
        assert report.outdated_count == 0

    def test_outdated_count_mixed(self):
        report = UpgradeReport(
            templates=[
                TemplateStatus("t1", "f1", "current"),
                TemplateStatus("t2", "f2", "outdated"),
                TemplateStatus("t3", "f3", "outdated"),
            ]
        )
        assert report.outdated_count == 2

    def test_to_dict_structure(self):
        report = UpgradeReport(
            templates=[
                TemplateStatus("tpl.py", "backend/tpl.py", "outdated",
                               current_version="2.0.0", project_version="1.0.0",
                               diff_lines=10),
            ]
        )
        d = report.to_dict()
        assert d["total_templates"] == 1
        assert d["outdated"] == 1
        assert d["templates"][0]["name"] == "tpl.py"
        assert d["templates"][0]["status"] == "outdated"
        assert d["templates"][0]["diff_lines"] == 10


# ---------------------------------------------------------------------------
# check_templates
# ---------------------------------------------------------------------------


class TestCheckTemplates:
    def _setup_template_and_project(self, tmp_path, template_name, template_text,
                                     project_text=None, backend="backend", frontend="frontend"):
        """Helper: set up a template file and optionally a project file."""
        # Create the template directory relative to the tool
        # We need to monkeypatch TEMPLATE_DIR, but check_templates reads
        # from TEMPLATE_DIR which is module-level. Instead, we create the
        # structure the function expects and monkeypatch.
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir(exist_ok=True)
        (templates_dir / template_name).write_text(template_text, encoding="utf-8")

        project_dir = tmp_path / "project"
        project_dir.mkdir(exist_ok=True)
        (project_dir / backend).mkdir(exist_ok=True)
        (project_dir / frontend).mkdir(exist_ok=True)

        if project_text is not None:
            dest_pattern = TEMPLATE_DESTINATIONS[template_name]
            dest_rel = dest_pattern.format(backend=backend, frontend=frontend)
            dest_file = project_dir / dest_rel
            dest_file.parent.mkdir(parents=True, exist_ok=True)
            dest_file.write_text(project_text, encoding="utf-8")

        return templates_dir, project_dir

    def test_missing_template_detected(self, tmp_path, monkeypatch):
        """File not in project -> status 'missing'."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text(
            "# Pineapple Pipeline v1.0.0\ncode", encoding="utf-8"
        )
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        project_dir.mkdir()

        report = check_templates(project_dir)
        rl = [t for t in report.templates if t.template_name == "rate_limiter.py"]
        assert len(rl) == 1
        assert rl[0].status == "missing"
        assert rl[0].current_version == "1.0.0"

    def test_current_version_detected(self, tmp_path, monkeypatch):
        """Same version in template and project -> status 'current'."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        content = "# Pineapple Pipeline v1.0.0\nrate limiter code"
        (templates_dir / "rate_limiter.py").write_text(content, encoding="utf-8")
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        dest = project_dir / "backend" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text(content, encoding="utf-8")

        report = check_templates(project_dir)
        rl = [t for t in report.templates if t.template_name == "rate_limiter.py"]
        assert len(rl) == 1
        assert rl[0].status == "current"
        assert rl[0].current_version == "1.0.0"
        assert rl[0].project_version == "1.0.0"

    def test_outdated_version_detected(self, tmp_path, monkeypatch):
        """Old version in project, new in template -> status 'outdated'."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text(
            "# Pineapple Pipeline v2.0.0\nnew code\nextra line", encoding="utf-8"
        )
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        dest = project_dir / "backend" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text("# Pineapple Pipeline v1.0.0\nold code", encoding="utf-8")

        report = check_templates(project_dir)
        rl = [t for t in report.templates if t.template_name == "rate_limiter.py"]
        assert len(rl) == 1
        assert rl[0].status == "outdated"
        assert rl[0].current_version == "2.0.0"
        assert rl[0].project_version == "1.0.0"
        assert rl[0].diff_lines > 0

    def test_custom_file_detected(self, tmp_path, monkeypatch):
        """Project file with no version header -> status 'custom'."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text(
            "# Pineapple Pipeline v1.0.0\ntemplate code", encoding="utf-8"
        )
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        dest = project_dir / "backend" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text("# My custom rate limiter\nno version header here", encoding="utf-8")

        report = check_templates(project_dir)
        rl = [t for t in report.templates if t.template_name == "rate_limiter.py"]
        assert len(rl) == 1
        assert rl[0].status == "custom"

    def test_auto_detect_backend_dir(self, tmp_path, monkeypatch):
        """Should detect 'server' as backend if 'backend' dir doesn't exist."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text(
            "# Pineapple Pipeline v1.0.0\ncode", encoding="utf-8"
        )
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        project_dir.mkdir()
        (project_dir / "server").mkdir()
        dest = project_dir / "server" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text("# Pineapple Pipeline v1.0.0\ncode", encoding="utf-8")

        report = check_templates(project_dir)
        rl = [t for t in report.templates if t.template_name == "rate_limiter.py"]
        assert len(rl) == 1
        assert rl[0].status == "current"
        assert "server/" in rl[0].project_file


# ---------------------------------------------------------------------------
# show_diff
# ---------------------------------------------------------------------------


class TestShowDiff:
    def test_diff_between_versions(self, tmp_path, monkeypatch):
        """Diff should show differences between project and template."""
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text(
            "# Pineapple Pipeline v2.0.0\nnew line\n", encoding="utf-8"
        )
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        dest = project_dir / "backend" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text("# Pineapple Pipeline v1.0.0\nold line\n", encoding="utf-8")

        diff = show_diff(project_dir, "rate_limiter.py")
        assert "---" in diff
        assert "+++" in diff
        assert "v1.0.0" in diff
        assert "v2.0.0" in diff

    def test_diff_unknown_template(self, tmp_path):
        result = show_diff(tmp_path, "nonexistent_template.py")
        assert "Unknown template" in result

    def test_diff_missing_project_file(self, tmp_path, monkeypatch):
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        (templates_dir / "rate_limiter.py").write_text("content", encoding="utf-8")
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        result = show_diff(tmp_path, "rate_limiter.py")
        assert "not found" in result.lower()

    def test_diff_missing_template_file(self, tmp_path, monkeypatch):
        templates_dir = tmp_path / "templates"
        templates_dir.mkdir()
        # Template file doesn't exist
        monkeypatch.setattr("pineapple_upgrade.TEMPLATE_DIR", templates_dir)

        project_dir = tmp_path / "project"
        dest = project_dir / "backend" / "app" / "middleware" / "rate_limiter.py"
        dest.parent.mkdir(parents=True)
        dest.write_text("content", encoding="utf-8")

        result = show_diff(project_dir, "rate_limiter.py")
        assert "not found" in result.lower()
