# Generated by Pineapple Pipeline v1.0.0
# Template: cache.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: Caching Layer
============================================
GAP-PPL-009 — App-level TTL Cache

Copy to your FastAPI project's middleware directory.
Configure cache instances for your specific use case.

Usage:
    from middleware.cache import TTLCache, get_cache_stats

    # Create a cache
    my_cache = TTLCache(max_size=64, ttl_seconds=3600, name="my_cache")

    # Use it
    result = my_cache.get(key)
    if result is None:
        result = expensive_computation()
        my_cache.set(key, result)

    # Wire stats into /api/health
    @app.get("/api/health")
    async def health():
        return {"cache": get_cache_stats()}

Placeholders:
    - Replace cache instances with your project's targets
    - Adjust max_size and ttl_seconds per cache
    - Add clear_project_cache() triggers to your mutation routes
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import time
from collections import OrderedDict
from typing import Any

logger = logging.getLogger("cache")


class TTLCache:
    """
    Thread/async-safe in-memory cache with TTL expiry and LRU eviction.

    Args:
        max_size: Maximum entries. Oldest accessed evicted on overflow.
        ttl_seconds: Time-to-live in seconds. 0 = never expires.
        name: Human-readable name for stats/logging.
    """

    def __init__(self, max_size: int = 64, ttl_seconds: int | float = 0, name: str = ""):
        self.max_size = max_size
        self.ttl_seconds = ttl_seconds
        self.name = name or f"cache_{id(self)}"
        self.hits = 0
        self.misses = 0
        self._entries: OrderedDict[str, tuple[Any, float]] = OrderedDict()
        self._lock = asyncio.Lock()

    def get(self, key: str) -> Any | None:
        entry = self._entries.get(key)
        if entry is None:
            self.misses += 1
            return None
        value, timestamp = entry
        if self.ttl_seconds > 0 and (time.time() - timestamp) > self.ttl_seconds:
            del self._entries[key]
            self.misses += 1
            return None
        self._entries.move_to_end(key)
        self.hits += 1
        return value

    def set(self, key: str, value: Any) -> None:
        if key in self._entries:
            self._entries.move_to_end(key)
            self._entries[key] = (value, time.time())
            return
        if len(self._entries) >= self.max_size:
            self._entries.popitem(last=False)
        self._entries[key] = (value, time.time())

    def clear(self) -> None:
        self._entries.clear()
        self.hits = 0
        self.misses = 0

    @property
    def size(self) -> int:
        return len(self._entries)

    def stats(self) -> dict:
        total = self.hits + self.misses
        return {
            "name": self.name,
            "size": self.size,
            "max_size": self.max_size,
            "hits": self.hits,
            "misses": self.misses,
            "hit_rate": round(self.hits / total, 3) if total > 0 else 0.0,
        }

    async def aget(self, key: str) -> Any | None:
        async with self._lock:
            return self.get(key)

    async def aset(self, key: str, value: Any) -> None:
        async with self._lock:
            self.set(key, value)


def make_hash_key(*args: Any) -> str:
    serialized = json.dumps(args, sort_keys=True, default=str)
    return hashlib.sha256(serialized.encode()).hexdigest()


# -- Configure your caches here --
# example_cache = TTLCache(max_size=64, ttl_seconds=3600, name="example")
# _ALL_CACHES = [example_cache]
_ALL_CACHES: list[TTLCache] = []


def get_cache_stats() -> dict:
    return {"caches": {c.name: c.stats() for c in _ALL_CACHES}}


def clear_all_caches() -> None:
    for c in _ALL_CACHES:
        c.clear()
