# Generated by Pineapple Pipeline v1.0.0
# Template: input_guardrails.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: Input Guardrails Middleware
=========================================================
GAP-PPL-005 — Prompt-Level Guardrails

Copy to your FastAPI project and import in main.py:
    from input_guardrails import InputGuardrailsMiddleware
    app.add_middleware(InputGuardrailsMiddleware)

This is a FIRST LINE of defense. It catches obvious injection
attempts before they reach the LLM. It is NOT a complete solution
(no single layer is). Use with output validation and model guardrails.
"""

import re
import logging
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse

logger = logging.getLogger("guardrails")

# ── Patterns that indicate prompt injection attempts ──
INJECTION_PATTERNS = [
    # Direct instruction override — "your" is optional BEFORE the qualifier
    r"ignore\s+(all\s+)?((your|the|my)\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?|context)",
    r"disregard\s+(all\s+)?((your|the|my)\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?)",
    r"forget\s+(all\s+)?((your|the|my)\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?)",
    # Also catch "disregard/forget/ignore your instructions" (no qualifier)
    r"(ignore|disregard|forget)\s+(all\s+)?your\s+(instructions?|prompts?|rules?)",
    # "override your instructions/safety/restrictions"
    r"override\s+((your|the|my|all)\s+)?(instructions?|prompts?|rules?|safety|restrictions?|guardrails?)",
    # System prompt extraction — "initial" and "text before" variants
    r"(show|reveal|display|print|output|repeat|tell|give)\s+(me\s+)?(your|the)\s+(system\s+|initial\s+)?(prompt|instructions?|rules?|context|text)",
    r"what\s+(are|were)\s+your\s+(initial\s+|system\s+)?(instructions?|rules?|prompt)",
    r"output\s+the\s+text\s+before\s+this",
    # Role override — "you are now" with article, preposition, or known jailbreak names
    r"you\s+are\s+now\s+(a|an|the|in)\s+",
    r"you\s+are\s+now\s+(DAN|evil|free|unrestricted|unfiltered|jailbroken|opposite)",
    r"act\s+as\s+(a|an|if)\s+",
    r"pretend\s+(to\s+be|you\s+are)",
    r"from\s+now\s+on\s+you\s+(are|will|must|should)",
    # Encoding bypass attempts
    r"base64\s*:",
    r"hex\s*:",
    r"\\x[0-9a-fA-F]{2}",  # hex escape sequences
    # Token smuggling
    r"\[INST\]",
    r"\[/INST\]",
    r"<\|im_start\|>",
    r"<\|im_end\|>",
    r"<<SYS>>",
    r"<</SYS>>",
]

# ── Compile for performance ──
COMPILED_PATTERNS = [re.compile(p, re.IGNORECASE) for p in INJECTION_PATTERNS]

# ── Thresholds ──
MAX_INPUT_LENGTH = 50_000  # characters
MIN_INPUT_LENGTH = 1       # reject empty


class InputGuardrailsMiddleware(BaseHTTPMiddleware):
    """FastAPI middleware that checks incoming requests for injection attempts."""

    async def dispatch(self, request: Request, call_next):
        # Only check POST requests to chat/generation endpoints
        if request.method == "POST" and any(
            p in request.url.path for p in ["/chat", "/generate", "/api/"]
        ):
            try:
                body = await request.body()
                text = body.decode("utf-8", errors="ignore").lower()

                # Length check
                if len(text) > MAX_INPUT_LENGTH:
                    logger.warning(f"Input too long: {len(text)} chars from {request.client.host}")
                    return JSONResponse(
                        status_code=400,
                        content={"error": "Input exceeds maximum length."},
                    )

                # Pattern check
                for pattern in COMPILED_PATTERNS:
                    match = pattern.search(text)
                    if match:
                        logger.warning(
                            f"Injection attempt blocked: '{match.group()[:50]}' "
                            f"from {request.client.host}"
                        )
                        return JSONResponse(
                            status_code=400,
                            content={"error": "Request could not be processed."},
                        )

            except Exception as e:
                logger.critical(f"Guardrail middleware error (BLOCKING): {e}")
                return JSONResponse(
                    status_code=500,
                    content={"error": "Security check failed. Request blocked."},
                )

        return await call_next(request)


def check_text(text: str) -> tuple[bool, str | None]:
    """
    Standalone check function for use outside middleware.
    Returns (is_safe, matched_pattern_or_none).
    """
    if len(text) > MAX_INPUT_LENGTH:
        return False, "Input too long"
    if len(text) < MIN_INPUT_LENGTH:
        return False, "Input too short"

    for pattern in COMPILED_PATTERNS:
        match = pattern.search(text.lower())
        if match:
            return False, match.group()[:50]

    return True, None
