# Generated by Pineapple Pipeline v1.0.0
# Template: mcp_server.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: MCP Server
=========================================
GAP-PPL-014 — MCP Exposure

Create a standalone MCP server that exposes your project's tools to AI agents.
Uses FastMCP (pip install fastmcp).

Usage:
    1. Copy this file to your project root
    2. Replace placeholder tools with your own
    3. Register in .mcp.json for Claude Code auto-discovery:
       {"mcpServers": {"my-tools": {"command": "python", "args": ["mcp_server.py"]}}}
    4. Run: python mcp_server.py

Placeholders:
    - Replace example_tool() with your project's tools
    - Update tool docstrings (they become the tool description in MCP)
    - Add imports for your project's engine classes
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from fastmcp import FastMCP

# Ensure your project is importable
sys.path.insert(0, str(Path(__file__).resolve().parent))

mcp = FastMCP(
    "My Project Tools",
    instructions="Replace with your project description",
)


def _make_response(success: bool, data: Any = None, error: str | None = None) -> str:
    """Create a structured JSON response string."""
    return json.dumps({"success": success, "data": data, "error": error}, default=str)


@mcp.tool()
async def example_tool(input_text: str) -> str:
    """
    Example tool — replace with your own.

    Args:
        input_text: Description of the input.

    Returns:
        JSON with structured response.
    """
    try:
        # Replace with your actual logic
        result = {"echo": input_text}
        return _make_response(success=True, data=result)
    except Exception as e:
        return _make_response(success=False, error=str(e))


if __name__ == "__main__":
    mcp.run()
