# Generated by Pineapple Pipeline v1.0.0
# Template: observability.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: Observability Setup
==================================================
GAP-PPL-003 — Observability / Tracing with LangFuse

Copy to your FastAPI project and import in main.py:
    from observability import setup_observability, observe_llm_call

Usage in your LLM calling code:
    result = await observe_llm_call(
        name="generate_code",
        model="gemini-2.5-flash",
        input_text=prompt,
        call_fn=lambda: llm_client.generate(prompt),
    )

Model costs loaded from data/model_costs.yaml (if present), with hardcoded
fallback defaults. Add/remove models by editing the YAML file — no code
changes needed. Runtime registration via register_model() / unregister_model().

Placeholders:
    None — configured via environment variables:
      LANGFUSE_SECRET_KEY, LANGFUSE_PUBLIC_KEY, LANGFUSE_HOST
"""

import os
import time
import logging
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger("observability")

# ── Try to import LangFuse, fall back to logging if not installed ──
try:
    from langfuse import Langfuse
    from langfuse.decorators import observe, langfuse_context
    LANGFUSE_AVAILABLE = True
except ImportError:
    LANGFUSE_AVAILABLE = False
    logger.info("LangFuse not installed. Using log-only observability.")


# ── Global state ──
_langfuse_client = None
_cost_log: list[dict] = []


def setup_observability() -> bool:
    """Initialize observability. Call once at app startup."""
    global _langfuse_client

    if not LANGFUSE_AVAILABLE:
        logger.info("Observability: log-only mode (pip install langfuse to enable tracing)")
        return False

    secret = os.getenv("LANGFUSE_SECRET_KEY")
    public = os.getenv("LANGFUSE_PUBLIC_KEY")
    host = os.getenv("LANGFUSE_HOST", "https://cloud.langfuse.com")

    if not secret or not public:
        logger.info("Observability: log-only mode (set LANGFUSE_SECRET_KEY and LANGFUSE_PUBLIC_KEY)")
        return False

    _langfuse_client = Langfuse(
        secret_key=secret,
        public_key=public,
        host=host,
    )
    logger.info(f"Observability: LangFuse tracing enabled ({host})")
    return True


# ── Cost tracking (works with or without LangFuse) ──

# Hardcoded fallback — used when model_costs.yaml is missing or unreadable.
_DEFAULT_MODEL_COSTS: dict[str, dict[str, float]] = {
    # Anthropic
    "claude-sonnet-4-20250514": {"input": 3.00, "output": 15.00},
    "claude-sonnet-4": {"input": 3.00, "output": 15.00},
    "claude-opus-4": {"input": 15.00, "output": 75.00},
    # Google
    "gemini-2.5-flash": {"input": 0.075, "output": 0.30},
    "gemini-2.5-pro": {"input": 1.25, "output": 10.00},
    # Groq (hosted Llama)
    "llama-3.3-70b-versatile": {"input": 0.59, "output": 0.79},
    # xAI
    "grok-3-mini": {"input": 0.30, "output": 0.50},
    # OpenAI
    "gpt-4o": {"input": 2.50, "output": 10.00},
    "gpt-4o-mini": {"input": 0.15, "output": 0.60},
}

# Unknown models fall back to this safe overestimate
_UNKNOWN_MODEL_COST = {"input": 1.0, "output": 3.0}


def _load_model_costs() -> dict[str, dict[str, float]]:
    """
    Load model costs from YAML config file, falling back to hardcoded defaults.

    Search order:
      1. MODEL_COSTS_PATH environment variable (absolute path)
      2. data/model_costs.yaml relative to the backend root
      3. Hardcoded _DEFAULT_MODEL_COSTS
    """
    try:
        import yaml
    except ImportError:
        logger.debug("PyYAML not installed; using hardcoded model costs")
        return dict(_DEFAULT_MODEL_COSTS)

    # Check env var first
    env_path = os.getenv("MODEL_COSTS_PATH")
    if env_path:
        yaml_path = Path(env_path)
    else:
        # Resolve relative to this file: middleware/ -> app/ -> backend/ -> data/
        yaml_path = Path(__file__).resolve().parent.parent.parent / "data" / "model_costs.yaml"

    if not yaml_path.exists():
        logger.debug("model_costs.yaml not found at %s; using hardcoded defaults", yaml_path)
        return dict(_DEFAULT_MODEL_COSTS)

    try:
        raw = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            logger.warning("model_costs.yaml has unexpected format; using hardcoded defaults")
            return dict(_DEFAULT_MODEL_COSTS)

        # Validate each entry has input/output keys
        costs: dict[str, dict[str, float]] = {}
        for model, pricing in raw.items():
            if isinstance(pricing, dict) and "input" in pricing and "output" in pricing:
                costs[model] = {"input": float(pricing["input"]), "output": float(pricing["output"])}
            else:
                logger.warning("Skipping malformed model cost entry: %s", model)

        logger.info("Loaded %d model costs from %s", len(costs), yaml_path)
        return costs

    except Exception as e:
        logger.warning("Failed to load model_costs.yaml (%s); using hardcoded defaults", e)
        return dict(_DEFAULT_MODEL_COSTS)


# Loaded once at import time; mutated by register_model / unregister_model
MODEL_COSTS: dict[str, dict[str, float]] = _load_model_costs()


def register_model(model: str, input_cost: float, output_cost: float) -> None:
    """
    Register (or update) a model's cost at runtime.

    Args:
        model: Model identifier (e.g. "gemini-2.5-flash").
        input_cost: Cost per 1M input tokens in USD.
        output_cost: Cost per 1M output tokens in USD.
    """
    MODEL_COSTS[model] = {"input": input_cost, "output": output_cost}
    logger.info("Registered model cost: %s (input=$%.3f, output=$%.3f per 1M tokens)", model, input_cost, output_cost)


def unregister_model(model: str) -> bool:
    """
    Remove a model from the cost registry.

    Returns True if the model was found and removed, False if it wasn't registered.
    """
    if model in MODEL_COSTS:
        del MODEL_COSTS[model]
        logger.info("Unregistered model cost: %s", model)
        return True
    return False


def list_models() -> dict[str, dict[str, float]]:
    """Return a copy of the current model cost registry."""
    return dict(MODEL_COSTS)


def estimate_cost(model: str, input_tokens: int, output_tokens: int) -> float:
    """Estimate cost in USD for an LLM call."""
    costs = MODEL_COSTS.get(model, _UNKNOWN_MODEL_COST)
    return (input_tokens * costs["input"] + output_tokens * costs["output"]) / 1_000_000


def log_llm_call(
    name: str,
    model: str,
    input_tokens: int = 0,
    output_tokens: int = 0,
    latency_ms: float = 0,
    success: bool = True,
    error: str | None = None,
):
    """Log an LLM call for cost tracking. Works without LangFuse."""
    cost = estimate_cost(model, input_tokens, output_tokens)

    entry = {
        "name": name,
        "model": model,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "cost_usd": round(cost, 6),
        "latency_ms": round(latency_ms, 1),
        "success": success,
        "error": error,
        "timestamp": time.time(),
    }
    _cost_log.append(entry)

    level = logging.INFO if success else logging.WARNING
    logger.log(
        level,
        f"LLM call: {name} | {model} | "
        f"{input_tokens}+{output_tokens} tokens | "
        f"${cost:.4f} | {latency_ms:.0f}ms | "
        f"{'OK' if success else f'FAIL: {error}'}"
    )

    return entry


async def observe_llm_call(
    name: str,
    model: str,
    input_text: str,
    call_fn: Callable,
    input_tokens: int = 0,
    output_tokens: int = 0,
) -> Any:
    """
    Execute an LLM call with observability wrapping.
    Works with or without LangFuse.
    """
    start = time.time()
    error = None
    success = True
    result = None

    try:
        result = await call_fn() if callable(call_fn) else call_fn
    except Exception as e:
        error = str(e)
        success = False
        raise
    finally:
        latency = (time.time() - start) * 1000
        log_llm_call(
            name=name,
            model=model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            latency_ms=latency,
            success=success,
            error=error,
        )

    return result


def get_cost_summary() -> dict:
    """Get cost summary for the current session."""
    if not _cost_log:
        return {"total_calls": 0, "total_cost_usd": 0, "calls": []}

    total_cost = sum(e["cost_usd"] for e in _cost_log)
    total_tokens = sum(e["input_tokens"] + e["output_tokens"] for e in _cost_log)
    failed = sum(1 for e in _cost_log if not e["success"])

    return {
        "total_calls": len(_cost_log),
        "total_cost_usd": round(total_cost, 4),
        "total_tokens": total_tokens,
        "failed_calls": failed,
        "avg_latency_ms": round(
            sum(e["latency_ms"] for e in _cost_log) / len(_cost_log), 1
        ),
        "by_model": _group_by_model(),
        "calls": _cost_log[-20:],  # last 20 calls
    }


def _group_by_model() -> dict:
    """Group cost data by model."""
    models: dict[str, dict] = {}
    for entry in _cost_log:
        m = entry["model"]
        if m not in models:
            models[m] = {"calls": 0, "cost_usd": 0, "tokens": 0}
        models[m]["calls"] += 1
        models[m]["cost_usd"] += entry["cost_usd"]
        models[m]["tokens"] += entry["input_tokens"] + entry["output_tokens"]
    return models
