# Generated by Pineapple Pipeline v1.0.0
# Template: rate_limiter.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: Rate Limiter Middleware
=====================================================
GAP-PPL-013 — Rate Limiting & Quotas

Copy to your FastAPI project and import in main.py:
    from rate_limiter import setup_rate_limiting
    setup_rate_limiting(app)

Placeholders:
    {{DEFAULT_LIMIT}}  - Default rate limit (default: "60/minute")
    {{CHAT_LIMIT}}     - Chat endpoint limit (default: "10/minute")
    {{EXPORT_LIMIT}}   - Export endpoint limit (default: "5/minute")
"""

from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse


def setup_rate_limiting(app: FastAPI, default_limit: str = "{{DEFAULT_LIMIT}}"):
    """Attach rate limiting to a FastAPI app."""

    limiter = Limiter(
        key_func=get_remote_address,
        default_limits=[default_limit],
        storage_uri="memory://",  # Use "redis://localhost:6379" for multi-process
    )
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

    return limiter


# ── Per-route decorators (use in your route files) ──
# Example:
#
#   from rate_limiter import limiter
#
#   @app.post("/api/chat")
#   @limiter.limit("10/minute")
#   async def chat(request: Request, ...):
#       ...
#
#   @app.post("/api/export")
#   @limiter.limit("5/minute")
#   async def export(request: Request, ...):
#       ...
