# Generated by Pineapple Pipeline v1.0.0
# Template: resilience.py
# Do not edit directly -- run `pineapple upgrade` to get latest version.
"""
Production Pipeline Template: Resilience Patterns
===================================================
GAP-PPL-008 — Error Recovery / Resilience

Copy to your project. Use the decorators on any function that calls
external services (LLM APIs, databases, file systems).

Usage:
    from resilience import with_retry, with_circuit_breaker, with_fallback

    @with_retry(max_attempts=3)
    async def call_llm(prompt):
        return await client.generate(prompt)

    @with_circuit_breaker(failure_threshold=3, recovery_timeout=60)
    async def call_vlm(image_path):
        return await vlm_client.critique(image_path)

    @with_fallback(fallback_value={"status": "degraded", "message": "Service temporarily unavailable"})
    async def get_analysis(data):
        return await external_service.analyze(data)
"""

import asyncio
import logging
import time
from enum import Enum
from functools import wraps
from typing import Any, Callable

logger = logging.getLogger("resilience")


# ══════════════════════════════════════════════════
# Retry with exponential backoff
# ══════════════════════════════════════════════════

def with_retry(
    max_attempts: int = 3,
    base_delay: float = 1.0,
    max_delay: float = 30.0,
    retryable_exceptions: tuple = (Exception,),
):
    """Retry a function with exponential backoff."""

    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            last_exception = None
            for attempt in range(1, max_attempts + 1):
                try:
                    return await func(*args, **kwargs)
                except retryable_exceptions as e:
                    last_exception = e
                    if attempt == max_attempts:
                        logger.error(
                            f"{func.__name__}: all {max_attempts} attempts failed. "
                            f"Last error: {e}"
                        )
                        raise
                    delay = min(base_delay * (2 ** (attempt - 1)), max_delay)
                    logger.warning(
                        f"{func.__name__}: attempt {attempt}/{max_attempts} failed "
                        f"({e}). Retrying in {delay:.1f}s..."
                    )
                    await asyncio.sleep(delay)
            raise last_exception

        return wrapper
    return decorator


# ══════════════════════════════════════════════════
# Circuit Breaker
# ══════════════════════════════════════════════════

class CircuitState(Enum):
    CLOSED = "closed"      # Normal operation
    OPEN = "open"          # Failing, reject calls
    HALF_OPEN = "half_open"  # Testing if recovered


class CircuitBreaker:
    """Simple circuit breaker implementation."""

    def __init__(
        self,
        name: str,
        failure_threshold: int = 3,
        recovery_timeout: float = 60.0,
    ):
        self.name = name
        self.failure_threshold = failure_threshold
        self.recovery_timeout = recovery_timeout
        self.state = CircuitState.CLOSED
        self.failure_count = 0
        self.last_failure_time = 0.0
        self.success_count = 0

    def can_execute(self) -> bool:
        if self.state == CircuitState.CLOSED:
            return True
        if self.state == CircuitState.OPEN:
            if time.time() - self.last_failure_time >= self.recovery_timeout:
                self.state = CircuitState.HALF_OPEN
                logger.info(f"Circuit {self.name}: HALF_OPEN (testing recovery)")
                return True
            return False
        if self.state == CircuitState.HALF_OPEN:
            return True
        return False

    def record_success(self):
        if self.state == CircuitState.HALF_OPEN:
            self.state = CircuitState.CLOSED
            self.failure_count = 0
            logger.info(f"Circuit {self.name}: CLOSED (recovered)")
        self.success_count += 1

    def record_failure(self):
        self.failure_count += 1
        self.last_failure_time = time.time()
        if self.failure_count >= self.failure_threshold:
            self.state = CircuitState.OPEN
            logger.warning(
                f"Circuit {self.name}: OPEN after {self.failure_count} failures. "
                f"Will retry in {self.recovery_timeout}s."
            )

    def get_status(self) -> dict:
        return {
            "name": self.name,
            "state": self.state.value,
            "failure_count": self.failure_count,
            "success_count": self.success_count,
        }


# Global circuit breaker registry
_breakers: dict[str, CircuitBreaker] = {}


def with_circuit_breaker(
    failure_threshold: int = 3,
    recovery_timeout: float = 60.0,
):
    """Wrap a function with circuit breaker protection."""

    def decorator(func):
        name = func.__name__
        _breakers[name] = CircuitBreaker(
            name=name,
            failure_threshold=failure_threshold,
            recovery_timeout=recovery_timeout,
        )

        @wraps(func)
        async def wrapper(*args, **kwargs):
            breaker = _breakers[name]
            if not breaker.can_execute():
                raise CircuitOpenError(
                    f"Circuit {name} is OPEN. Service unavailable. "
                    f"Retry after {breaker.recovery_timeout}s."
                )
            try:
                result = await func(*args, **kwargs)
                breaker.record_success()
                return result
            except Exception as e:
                breaker.record_failure()
                raise

        return wrapper
    return decorator


class CircuitOpenError(Exception):
    """Raised when circuit breaker is open."""
    pass


# ══════════════════════════════════════════════════
# Fallback / Graceful Degradation
# ══════════════════════════════════════════════════

def with_fallback(fallback_value: Any = None, fallback_fn: Callable = None):
    """Return a fallback value if the function fails."""

    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except Exception as e:
                logger.warning(
                    f"{func.__name__}: failed ({e}). Using fallback."
                )
                if fallback_fn:
                    return fallback_fn(*args, **kwargs)
                return fallback_value

        return wrapper
    return decorator


# ══════════════════════════════════════════════════
# Health reporting
# ══════════════════════════════════════════════════

def get_all_circuit_states() -> list[dict]:
    """Get status of all circuit breakers. Use in /health endpoint."""
    return [b.get_status() for b in _breakers.values()]
