"""
pineapple_evolve.py -- Post-session automation for the Pineapple Pipeline.

Handles post-session housekeeping: session handoffs, bible updates, external
service feeds. Each step is independent -- any failure is logged but doesn't
block others.

Usage:
    py -3.12 production-pipeline/tools/pineapple_evolve.py <project-path> \
        [--session-file PATH] [--decisions TEXT] [--run-id UUID] [--json]

Exit code: 0 if all steps done/skipped, 1 if any step errored.
"""
from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

logger = logging.getLogger("pineapple.evolve")


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class StepResult:
    name: str
    status: Literal["done", "skip", "error"]
    message: str
    duration_ms: float = 0


@dataclass
class EvolveReport:
    steps: list[StepResult] = field(default_factory=list)

    @property
    def all_done(self) -> bool:
        return all(s.status != "error" for s in self.steps)

    def to_dict(self) -> dict:
        return {
            "overall": "done" if self.all_done else "partial",
            "steps": [
                {
                    "name": s.name,
                    "status": s.status,
                    "message": s.message,
                    "duration_ms": s.duration_ms,
                }
                for s in self.steps
            ],
        }


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

def step_1_session_handoff(
    project_path: Path, session_file: Path | None = None
) -> StepResult:
    """Write session handoff file from git log if not provided."""
    start = time.time()

    sessions_dir = project_path / "sessions"
    today = datetime.now().strftime("%Y-%m-%d")

    # If user provided a session file, just verify it exists
    if session_file and session_file.is_file():
        return StepResult(
            "Session handoff",
            "done",
            f"Using provided: {session_file}",
            (time.time() - start) * 1000,
        )

    # Generate from git log
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-20", "--since=12 hours ago"],
            cwd=str(project_path),
            capture_output=True,
            text=True,
            timeout=10,
        )
        commits = result.stdout.strip()
        if not commits:
            return StepResult(
                "Session handoff",
                "skip",
                "No recent commits to summarize",
                (time.time() - start) * 1000,
            )

        sessions_dir.mkdir(parents=True, exist_ok=True)

        # Check if file already exists (append a letter suffix)
        handoff_path = sessions_dir / f"{today}.md"
        suffix = ""
        while handoff_path.is_file():
            suffix = chr(ord(suffix or "`") + 1)  # a, b, c, ...
            handoff_path = sessions_dir / f"{today}{suffix}.md"

        content = f"# Session Handoff -- {today}{suffix}\n\n"
        content += "## Recent Commits\n```\n"
        content += commits
        content += "\n```\n\n"
        content += "## Status\n- Generated by pineapple evolve\n"

        handoff_path.write_text(content, encoding="utf-8")
        return StepResult(
            "Session handoff",
            "done",
            f"Written: {handoff_path}",
            (time.time() - start) * 1000,
        )
    except Exception as e:
        return StepResult(
            "Session handoff", "error", str(e), (time.time() - start) * 1000
        )


def step_2_update_bible(project_path: Path, run_id: str = "") -> StepResult:
    """Update project bible based on verification results."""
    start = time.time()

    # Find bible file
    projects_dir = project_path / "projects"
    if not projects_dir.is_dir():
        return StepResult(
            "Update bible",
            "skip",
            "No projects/ directory",
            (time.time() - start) * 1000,
        )

    bible_files = list(projects_dir.glob("*-bible*.yaml")) + list(
        projects_dir.glob("*-bible*.yml")
    )
    if not bible_files:
        return StepResult(
            "Update bible",
            "skip",
            "No bible file found",
            (time.time() - start) * 1000,
        )

    # Check for verification record
    verify_dir = project_path / ".pineapple" / "verify"
    if not verify_dir.is_dir():
        return StepResult(
            "Update bible",
            "skip",
            "No verification records",
            (time.time() - start) * 1000,
        )

    records = list(verify_dir.glob("*.json"))
    if not records:
        return StepResult(
            "Update bible",
            "skip",
            "No verification records found",
            (time.time() - start) * 1000,
        )

    # Just report -- actual bible editing requires YAML manipulation
    # that's project-specific
    return StepResult(
        "Update bible",
        "done",
        f"Found {len(bible_files)} bible(s), {len(records)} verification record(s). Manual review recommended.",
        (time.time() - start) * 1000,
    )


def step_3_append_decisions(
    project_path: Path, decisions: str | None = None
) -> StepResult:
    """Append new decisions to decisions.md."""
    start = time.time()

    if not decisions:
        return StepResult(
            "Append decisions",
            "skip",
            "No decisions provided",
            (time.time() - start) * 1000,
        )

    # Look for decisions file in memory dir or project root
    decisions_paths = [
        project_path / "memory" / "decisions.md",
        project_path / "decisions.md",
    ]

    target = None
    for p in decisions_paths:
        if p.is_file():
            target = p
            break

    if target is None:
        # Create in memory dir if it exists, otherwise project root
        memory_dir = project_path / "memory"
        if memory_dir.is_dir():
            target = memory_dir / "decisions.md"
        else:
            target = project_path / "decisions.md"

    try:
        today = datetime.now().strftime("%Y-%m-%d")
        entry = f"\n## {today}\n{decisions}\n"

        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "a", encoding="utf-8") as f:
            f.write(entry)

        return StepResult(
            "Append decisions",
            "done",
            f"Appended to {target}",
            (time.time() - start) * 1000,
        )
    except Exception as e:
        return StepResult(
            "Append decisions", "error", str(e), (time.time() - start) * 1000
        )


def step_4_feed_mem0(
    project_path: Path, session_file: Path | None = None
) -> StepResult:
    """Feed Mem0 with session facts (if running)."""
    start = time.time()

    try:
        import urllib.request

        req = urllib.request.Request("http://localhost:8080/health", method="GET")
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        return StepResult(
            "Feed Mem0",
            "skip",
            "Mem0 not running",
            (time.time() - start) * 1000,
        )

    # Mem0 is running -- but actual feeding requires the session content
    # and Mem0 API
    return StepResult(
        "Feed Mem0",
        "skip",
        "Mem0 reachable but auto-feed not yet implemented",
        (time.time() - start) * 1000,
    )


def step_5_feed_neo4j(project_path: Path) -> StepResult:
    """Update Neo4j component graph (if running)."""
    start = time.time()

    try:
        import socket

        sock = socket.create_connection(("localhost", 7687), timeout=3)
        sock.close()
    except Exception:
        return StepResult(
            "Feed Neo4j",
            "skip",
            "Neo4j not running",
            (time.time() - start) * 1000,
        )

    return StepResult(
        "Feed Neo4j",
        "skip",
        "Neo4j reachable but auto-feed not yet implemented",
        (time.time() - start) * 1000,
    )


def step_6_update_eval_baselines(project_path: Path) -> StepResult:
    """Update DeepEval baselines from latest verification."""
    start = time.time()

    try:
        import deepeval  # noqa: F401
    except ImportError:
        return StepResult(
            "Update baselines",
            "skip",
            "deepeval not installed",
            (time.time() - start) * 1000,
        )

    return StepResult(
        "Update baselines",
        "skip",
        "DeepEval installed but baseline update not yet implemented",
        (time.time() - start) * 1000,
    )


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def run_evolve(
    project_path: Path,
    session_file: Path | None = None,
    decisions: str | None = None,
    run_id: str = "",
) -> EvolveReport:
    """Run all post-session steps. Each step is independent -- failures don't block others."""
    report = EvolveReport()

    report.steps.append(step_1_session_handoff(project_path, session_file))
    report.steps.append(step_2_update_bible(project_path, run_id))
    report.steps.append(step_3_append_decisions(project_path, decisions))
    report.steps.append(step_4_feed_mem0(project_path, session_file))
    report.steps.append(step_5_feed_neo4j(project_path))
    report.steps.append(step_6_update_eval_baselines(project_path))

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Pineapple Pipeline Post-Session Automation"
    )
    parser.add_argument("project_path", type=Path, help="Path to project root")
    parser.add_argument(
        "--session-file", type=Path, help="Existing session handoff file"
    )
    parser.add_argument("--decisions", help="Decisions text to append")
    parser.add_argument("--run-id", default="", help="Pipeline run ID")
    parser.add_argument("--json", action="store_true", help="JSON output")

    args = parser.parse_args()

    report = run_evolve(
        args.project_path, args.session_file, args.decisions, args.run_id
    )

    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        print("\nPineapple Evolve v1.0.0")
        print("========================")
        for step in report.steps:
            status_str = {"done": " DONE ", "skip": " SKIP ", "error": "ERROR "}[
                step.status
            ]
            print(f"  [{status_str}] {step.name}: {step.message}")
        print(
            f"\nOverall: {'COMPLETE' if report.all_done else 'PARTIAL (some steps had errors)'}"
        )

    sys.exit(0 if report.all_done else 1)
