"""
pineapple_evolve.py -- Post-session automation for the Pineapple Pipeline.

Handles post-session housekeeping: session handoffs, bible updates, external
service feeds. Each step is independent -- any failure is logged but doesn't
block others.

Usage:
    py -3.12 production-pipeline/tools/pineapple_evolve.py <project-path> \
        [--session-file PATH] [--decisions TEXT] [--run-id UUID] [--json]

Exit code: 0 if all steps done/skipped, 1 if any step errored.
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal

# httpx is an optional dep (listed under [doctor] extras)
try:
    import httpx as _httpx
    _HTTPX_AVAILABLE = True
except ImportError:
    _HTTPX_AVAILABLE = False

_HTTP_TIMEOUT = 5.0  # seconds for every external call

logger = logging.getLogger("pineapple.evolve")


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class StepResult:
    name: str
    status: Literal["done", "skip", "error"]
    message: str
    duration_ms: float = 0


@dataclass
class EvolveReport:
    steps: list[StepResult] = field(default_factory=list)

    @property
    def all_done(self) -> bool:
        return all(s.status != "error" for s in self.steps)

    def to_dict(self) -> dict:
        return {
            "overall": "done" if self.all_done else "partial",
            "steps": [
                {
                    "name": s.name,
                    "status": s.status,
                    "message": s.message,
                    "duration_ms": s.duration_ms,
                }
                for s in self.steps
            ],
        }


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------


def step_1_session_handoff(project_path: Path, session_file: Path | None = None) -> StepResult:
    """Write session handoff file from git log if not provided."""
    start = time.time()

    sessions_dir = project_path / "sessions"
    today = datetime.now().strftime("%Y-%m-%d")

    # If user provided a session file, just verify it exists
    if session_file and session_file.is_file():
        return StepResult(
            "Session handoff",
            "done",
            f"Using provided: {session_file}",
            (time.time() - start) * 1000,
        )

    # Generate from git log
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-20", "--since=12 hours ago"],
            cwd=str(project_path),
            capture_output=True,
            text=True,
            timeout=10,
        )
        commits = result.stdout.strip()
        if not commits:
            return StepResult(
                "Session handoff",
                "skip",
                "No recent commits to summarize",
                (time.time() - start) * 1000,
            )

        sessions_dir.mkdir(parents=True, exist_ok=True)

        # Check if file already exists (append a letter suffix)
        handoff_path = sessions_dir / f"{today}.md"
        suffix = ""
        while handoff_path.is_file():
            suffix = chr(ord(suffix or "`") + 1)  # a, b, c, ...
            handoff_path = sessions_dir / f"{today}{suffix}.md"

        content = f"# Session Handoff -- {today}{suffix}\n\n"
        content += "## Recent Commits\n```\n"
        content += commits
        content += "\n```\n\n"
        content += "## Status\n- Generated by pineapple evolve\n"

        handoff_path.write_text(content, encoding="utf-8")
        return StepResult(
            "Session handoff",
            "done",
            f"Written: {handoff_path}",
            (time.time() - start) * 1000,
        )
    except Exception as e:
        return StepResult("Session handoff", "error", str(e), (time.time() - start) * 1000)


def step_2_update_bible(project_path: Path, run_id: str = "") -> StepResult:
    """Update project bible based on verification results."""
    start = time.time()

    # Find bible file
    projects_dir = project_path / "projects"
    if not projects_dir.is_dir():
        return StepResult(
            "Update bible",
            "skip",
            "No projects/ directory",
            (time.time() - start) * 1000,
        )

    bible_files = list(projects_dir.glob("*-bible*.yaml")) + list(projects_dir.glob("*-bible*.yml"))
    if not bible_files:
        return StepResult(
            "Update bible",
            "skip",
            "No bible file found",
            (time.time() - start) * 1000,
        )

    # Check for verification record
    verify_dir = project_path / ".pineapple" / "verify"
    if not verify_dir.is_dir():
        return StepResult(
            "Update bible",
            "skip",
            "No verification records",
            (time.time() - start) * 1000,
        )

    records = list(verify_dir.glob("*.json"))
    if not records:
        return StepResult(
            "Update bible",
            "skip",
            "No verification records found",
            (time.time() - start) * 1000,
        )

    # Just report -- actual bible editing requires YAML manipulation
    # that's project-specific
    return StepResult(
        "Update bible",
        "done",
        f"Found {len(bible_files)} bible(s), {len(records)} verification record(s). Manual review recommended.",
        (time.time() - start) * 1000,
    )


def step_3_append_decisions(project_path: Path, decisions: str | None = None) -> StepResult:
    """Append new decisions to decisions.md."""
    start = time.time()

    if not decisions:
        return StepResult(
            "Append decisions",
            "skip",
            "No decisions provided",
            (time.time() - start) * 1000,
        )

    # Look for decisions file in memory dir or project root
    decisions_paths = [
        project_path / "memory" / "decisions.md",
        project_path / "decisions.md",
    ]

    target = None
    for p in decisions_paths:
        if p.is_file():
            target = p
            break

    if target is None:
        # Create in memory dir if it exists, otherwise project root
        memory_dir = project_path / "memory"
        if memory_dir.is_dir():
            target = memory_dir / "decisions.md"
        else:
            target = project_path / "decisions.md"

    try:
        today = datetime.now().strftime("%Y-%m-%d")
        entry = f"\n## {today}\n{decisions}\n"

        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "a", encoding="utf-8") as f:
            f.write(entry)

        return StepResult(
            "Append decisions",
            "done",
            f"Appended to {target}",
            (time.time() - start) * 1000,
        )
    except Exception as e:
        return StepResult("Append decisions", "error", str(e), (time.time() - start) * 1000)


def _extract_facts_from_session(session_file: Path | None, project_path: Path) -> list[str]:
    """Read the latest session handoff and pull out bullet-style facts."""
    target = session_file

    # Fall back to most recently written sessions/<date>.md
    if target is None or not target.is_file():
        sessions_dir = project_path / "sessions"
        if sessions_dir.is_dir():
            candidates = sorted(sessions_dir.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
            if candidates:
                target = candidates[0]

    if target is None or not target.is_file():
        return []

    facts: list[str] = []
    text = target.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        stripped = line.strip()
        # Treat markdown list items and heading lines as facts
        if stripped.startswith(("- ", "* ", "+ ")) and len(stripped) > 4:
            facts.append(stripped[2:].strip())
        elif stripped.startswith("#") and len(stripped) > 2:
            facts.append(stripped.lstrip("#").strip())
    return facts


def step_4_feed_mem0(project_path: Path, session_file: Path | None = None) -> StepResult:
    """Feed Mem0 with session facts (if running)."""
    start = time.time()

    if not _HTTPX_AVAILABLE:
        return StepResult(
            "Feed Mem0",
            "skip",
            "httpx not installed -- skipping Mem0 feed",
            (time.time() - start) * 1000,
        )

    try:
        from pineapple_config import load_config
        cfg = load_config(project_path)
        mem0_url = cfg.services.mem0_url.rstrip("/")
    except Exception:
        mem0_url = "http://localhost:8080"

    # Reachability check
    try:
        resp = _httpx.get(f"{mem0_url}/health", timeout=_HTTP_TIMEOUT)
        resp.raise_for_status()
    except _httpx.ConnectError:
        return StepResult(
            "Feed Mem0",
            "skip",
            f"Mem0 not reachable at {mem0_url}",
            (time.time() - start) * 1000,
        )
    except _httpx.TimeoutException:
        return StepResult(
            "Feed Mem0",
            "skip",
            f"Mem0 health check timed out ({_HTTP_TIMEOUT}s)",
            (time.time() - start) * 1000,
        )
    except Exception as exc:
        return StepResult(
            "Feed Mem0",
            "skip",
            f"Mem0 health check failed: {exc}",
            (time.time() - start) * 1000,
        )

    facts = _extract_facts_from_session(session_file, project_path)
    if not facts:
        return StepResult(
            "Feed Mem0",
            "skip",
            "No facts to send (empty session file)",
            (time.time() - start) * 1000,
        )

    stored = 0
    errors: list[str] = []
    for fact in facts:
        payload = {
            "messages": [{"role": "user", "content": fact}],
            "user_id": "pineapple",
        }
        try:
            r = _httpx.post(
                f"{mem0_url}/v1/memories/",
                json=payload,
                timeout=_HTTP_TIMEOUT,
            )
            r.raise_for_status()
            stored += 1
            logger.debug("Mem0: stored fact %r", fact[:60])
        except _httpx.ConnectError as exc:
            errors.append(f"connect error: {exc}")
            break  # server went away mid-loop
        except _httpx.TimeoutException:
            errors.append(f"timeout storing fact: {fact[:40]!r}")
        except Exception as exc:
            errors.append(f"error storing {fact[:40]!r}: {exc}")

    if errors:
        logger.warning("Feed Mem0: %d errors -- %s", len(errors), errors[0])

    msg = f"Stored {stored}/{len(facts)} facts to {mem0_url}"
    if errors:
        msg += f" ({len(errors)} errors: {errors[0]})"
    logger.info("Feed Mem0: %s", msg)
    return StepResult(
        "Feed Mem0",
        "done" if stored > 0 or not errors else "error",
        msg,
        (time.time() - start) * 1000,
    )


def _extract_relationships(project_path: Path) -> list[tuple[str, str, str]]:
    """Scan the latest session + bible diffs for component relationships.

    Returns list of (source, rel_type, target) triples, e.g.
        ("TripleHelix", "USES", "PlanetaryGear")
    """
    relationships: list[tuple[str, str, str]] = []

    # Read most recent session file
    sessions_dir = project_path / "sessions"
    lines: list[str] = []
    if sessions_dir.is_dir():
        candidates = sorted(sessions_dir.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
        if candidates:
            lines = candidates[0].read_text(encoding="utf-8", errors="replace").splitlines()

    # Parse simple "A depends on B", "A uses B", "A modified" patterns
    import re as _re
    dep_pat = _re.compile(r"\b(\w[\w\s]*?)\s+(?:depends on|uses|requires|inherits from)\s+([\w][\w\s]*)", _re.I)
    mod_pat = _re.compile(r"\b(modified|created|updated|added):\s*([\w][\w\s\-\.]*)", _re.I)

    project_name = project_path.name or "Project"

    for line in lines:
        m = dep_pat.search(line)
        if m:
            src = m.group(1).strip()[:64]
            tgt = m.group(2).strip()[:64]
            rel = "DEPENDS_ON"
            if "uses" in line.lower():
                rel = "USES"
            elif "inherits" in line.lower():
                rel = "INHERITS_FROM"
            relationships.append((src, rel, tgt))

        m2 = mod_pat.search(line)
        if m2:
            action = m2.group(1).upper()
            component = m2.group(2).strip()[:64]
            rel_map = {
                "MODIFIED": "MODIFIED",
                "CREATED": "CREATED",
                "UPDATED": "MODIFIED",
                "ADDED": "CREATED",
            }
            relationships.append((project_name, rel_map.get(action, "MODIFIED"), component))

    return relationships[:50]  # cap at 50 to avoid flooding


def _build_neo4j_cypher(relationships: list[tuple[str, str, str]]) -> list[dict]:
    """Turn relationship triples into Neo4j transactional statements."""
    statements = []
    for src, rel, tgt in relationships:
        # MERGE avoids duplicate nodes/relationships
        cypher = (
            f"MERGE (a:Component {{name: $src}}) "
            f"MERGE (b:Component {{name: $tgt}}) "
            f"MERGE (a)-[:{rel}]->(b)"
        )
        statements.append({"statement": cypher, "parameters": {"src": src, "tgt": tgt}})
    return statements


def step_5_feed_neo4j(project_path: Path) -> StepResult:
    """Update Neo4j component graph (if running)."""
    start = time.time()

    if not _HTTPX_AVAILABLE:
        return StepResult(
            "Feed Neo4j",
            "skip",
            "httpx not installed -- skipping Neo4j feed",
            (time.time() - start) * 1000,
        )

    try:
        from pineapple_config import load_config
        cfg = load_config(project_path)
        # neo4j_url may be bolt:// -- swap to http for the HTTP API
        raw_url = cfg.services.neo4j_url
        if raw_url.startswith("bolt://"):
            http_url = raw_url.replace("bolt://", "http://", 1)
            # Default Neo4j HTTP port is 7474; bolt is 7687 -- adjust
            http_url = http_url.replace(":7687", ":7474")
        else:
            http_url = raw_url
        http_url = http_url.rstrip("/")
    except Exception:
        http_url = "http://localhost:7474"

    tx_url = f"{http_url}/db/neo4j/tx/commit"

    # Reachability check
    try:
        resp = _httpx.get(http_url, timeout=_HTTP_TIMEOUT)
        # Neo4j returns 200 on / — any non-connection-error means it's up
    except _httpx.ConnectError:
        return StepResult(
            "Feed Neo4j",
            "skip",
            f"Neo4j not reachable at {http_url}",
            (time.time() - start) * 1000,
        )
    except _httpx.TimeoutException:
        return StepResult(
            "Feed Neo4j",
            "skip",
            f"Neo4j health check timed out ({_HTTP_TIMEOUT}s)",
            (time.time() - start) * 1000,
        )
    except Exception as exc:
        return StepResult(
            "Feed Neo4j",
            "skip",
            f"Neo4j check failed: {exc}",
            (time.time() - start) * 1000,
        )

    relationships = _extract_relationships(project_path)
    if not relationships:
        return StepResult(
            "Feed Neo4j",
            "skip",
            "No component relationships found in session",
            (time.time() - start) * 1000,
        )

    statements = _build_neo4j_cypher(relationships)
    payload = {"statements": statements}

    try:
        r = _httpx.post(
            tx_url,
            json=payload,
            headers={"Content-Type": "application/json", "Accept": "application/json"},
            timeout=_HTTP_TIMEOUT,
        )
        r.raise_for_status()
        resp_data = r.json()
        neo4j_errors = resp_data.get("errors", [])
        if neo4j_errors:
            msg = f"Neo4j returned {len(neo4j_errors)} error(s): {neo4j_errors[0].get('message', '')}"
            logger.error("Feed Neo4j: %s", msg)
            return StepResult("Feed Neo4j", "error", msg, (time.time() - start) * 1000)

        msg = f"Sent {len(statements)} relationship(s) to {tx_url}"
        logger.info("Feed Neo4j: %s", msg)
        return StepResult("Feed Neo4j", "done", msg, (time.time() - start) * 1000)
    except _httpx.ConnectError as exc:
        return StepResult("Feed Neo4j", "skip", f"Neo4j disconnected mid-request: {exc}", (time.time() - start) * 1000)
    except Exception as exc:
        return StepResult("Feed Neo4j", "error", f"Neo4j TX failed: {exc}", (time.time() - start) * 1000)


def step_6_update_eval_baselines(project_path: Path) -> StepResult:
    """Update DeepEval baselines from latest verification record.

    Reads the most recent .pineapple/verify/*.json, compares test_count and
    layers_passed to the stored baseline at .pineapple/baselines.json, and
    updates the baseline when results improve (or creates it fresh).
    Does NOT require deepeval to be installed.
    """
    start = time.time()

    verify_dir = project_path / ".pineapple" / "verify"
    baselines_path = project_path / ".pineapple" / "baselines.json"

    if not verify_dir.is_dir():
        return StepResult(
            "Update baselines",
            "skip",
            "No .pineapple/verify/ directory",
            (time.time() - start) * 1000,
        )

    records = sorted(verify_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not records:
        return StepResult(
            "Update baselines",
            "skip",
            "No verification records in .pineapple/verify/",
            (time.time() - start) * 1000,
        )

    # Load latest verification record
    try:
        latest = json.loads(records[0].read_text(encoding="utf-8"))
    except Exception as exc:
        return StepResult(
            "Update baselines",
            "error",
            f"Failed to read verify record {records[0].name}: {exc}",
            (time.time() - start) * 1000,
        )

    current_test_count: int = int(latest.get("test_count", 0))
    current_layers: list[int] = list(latest.get("layers_passed", []))
    current_layer_count = len(current_layers)

    # Load existing baseline (if any)
    baseline: dict = {}
    if baselines_path.is_file():
        try:
            baseline = json.loads(baselines_path.read_text(encoding="utf-8"))
        except Exception:
            baseline = {}

    prev_test_count: int = int(baseline.get("test_count", 0))
    prev_layer_count: int = int(baseline.get("layers_passed_count", 0))

    # Decide whether to update
    improved = current_test_count > prev_test_count or current_layer_count > prev_layer_count
    regressed = current_test_count < prev_test_count or current_layer_count < prev_layer_count
    unchanged = not improved and not regressed

    if regressed:
        msg = (
            f"REGRESSION: test_count {prev_test_count} -> {current_test_count}, "
            f"layers {prev_layer_count} -> {current_layer_count}. Baseline NOT updated."
        )
        logger.warning("Update baselines: %s", msg)
        return StepResult("Update baselines", "error", msg, (time.time() - start) * 1000)

    if unchanged and baseline:
        msg = (
            f"No change: test_count={current_test_count}, layers_passed={current_layer_count}. "
            "Baseline unchanged."
        )
        logger.info("Update baselines: %s", msg)
        return StepResult("Update baselines", "skip", msg, (time.time() - start) * 1000)

    # Write updated baseline
    new_baseline = {
        "updated_at": datetime.now().isoformat(),
        "source_record": records[0].name,
        "test_count": current_test_count,
        "layers_passed_count": current_layer_count,
        "layers_passed": current_layers,
    }
    try:
        baselines_path.parent.mkdir(parents=True, exist_ok=True)
        baselines_path.write_text(json.dumps(new_baseline, indent=2), encoding="utf-8")
    except Exception as exc:
        return StepResult(
            "Update baselines",
            "error",
            f"Failed to write baselines.json: {exc}",
            (time.time() - start) * 1000,
        )

    if not baseline:
        msg = (
            f"Baseline created: test_count={current_test_count}, "
            f"layers_passed={current_layer_count}."
        )
    else:
        msg = (
            f"Improved: test_count {prev_test_count} -> {current_test_count}, "
            f"layers {prev_layer_count} -> {current_layer_count}. Baseline updated."
        )
    logger.info("Update baselines: %s", msg)
    return StepResult("Update baselines", "done", msg, (time.time() - start) * 1000)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def run_evolve(
    project_path: Path,
    session_file: Path | None = None,
    decisions: str | None = None,
    run_id: str = "",
) -> EvolveReport:
    """Run all post-session steps. Each step is independent -- failures don't block others."""
    report = EvolveReport()

    report.steps.append(step_1_session_handoff(project_path, session_file))
    report.steps.append(step_2_update_bible(project_path, run_id))
    report.steps.append(step_3_append_decisions(project_path, decisions))
    report.steps.append(step_4_feed_mem0(project_path, session_file))
    report.steps.append(step_5_feed_neo4j(project_path))
    report.steps.append(step_6_update_eval_baselines(project_path))

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pineapple Pipeline Post-Session Automation")
    parser.add_argument("project_path", type=Path, help="Path to project root")
    parser.add_argument("--session-file", type=Path, help="Existing session handoff file")
    parser.add_argument("--decisions", help="Decisions text to append")
    parser.add_argument("--run-id", default="", help="Pipeline run ID")
    parser.add_argument("--json", action="store_true", help="JSON output")

    args = parser.parse_args()

    report = run_evolve(args.project_path, args.session_file, args.decisions, args.run_id)

    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        print("\nPineapple Evolve v1.0.0")
        print("========================")
        for step in report.steps:
            status_str = {"done": " DONE ", "skip": " SKIP ", "error": "ERROR "}[step.status]
            print(f"  [{status_str}] {step.name}: {step.message}")
        print(f"\nOverall: {'COMPLETE' if report.all_done else 'PARTIAL (some steps had errors)'}")

    sys.exit(0 if report.all_done else 1)
